apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fa
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: .
    repoURL: https://github.com/satyamburhade/opg.git
    targetRevision: HEAD
