kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: busybox
  namespace: busybox
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 100%
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ConfigChange
  replicas: 2
  revisionHistoryLimit: 10
  test: false
  selector:
    deploymentconfig: busybox
  template:
    metadata:
      creationTimestamp: null
      labels:
        deploymentconfig: busybox
    spec:
      containers:
        - name: busybox
          image: busybox
          command:
            - /bin/sh
            - '-c'
            - while true ; do date; sleep 20; done;
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
