apiVersion: authorization.openshift.io/v1
kind: RoleBinding
metadata:
  name: example
  namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openshift-gitops-applicationset-controller
subjects:
- kind: ServiceAccount
  name: openshift-gitops-applicationset-controller
  namespace: openshift-gitops

